const MONTH = 0;
const OU = 1;
const EXPECTED = 5;
const TIMELY = 2;
const LATE = 3;

export const COLUMNS = {MONTH, OU, EXPECTED, TIMELY, LATE};

const SECONDARY_COLUMN_REPORTED_ON = 3;
const SECONDARY_COLUMN_TIMELINESS = 4;
const SECONDARY_COLUMN_VALUE_TIMELY = 'Timely';
const SECONDARY_COLUMN_VALUE_LATE = 'Late';

export const SECONDARY_COLUMNS = {
    REPORTED_ON: SECONDARY_COLUMN_REPORTED_ON,
    TIMELINESS: SECONDARY_COLUMN_TIMELINESS,
    VALUE_TIMELY: SECONDARY_COLUMN_VALUE_TIMELY,
    VALUE_LATE: SECONDARY_COLUMN_VALUE_LATE,
}


const LINE = 'line';
const COLUMN = 'column';
export const CHARTS = {LINE, COLUMN}
